version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 37192541
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
